import std/[os, strutils, algorithm]

## Plugin aggregator generator: scans `commands/*/main.nim`
## and produces `generated/plugins_agg.nim` with the imports and the
## register calls. No runtime dynamism: type safety, native async.
## Invoked by `nimble build` (build task) before compilation.

let root = getCurrentDir()
let cmdDir = root / "commands"
let outDir = root / "generated"
let outFile = outDir / "plugins_agg.nim"

var names: seq[string] = @[]
if dirExists(cmdDir):
  for kind, path in walkDir(cmdDir):
    if kind == pcDir and fileExists(path / "main.nim"):
      let (_, name, _) = splitFile(path)
      names.add(name)
names = names.sorted()

createDir(outDir)

var agg = ""
agg.add("# AUTO-GENERATED by tools/gen_plugins.nim - DO NOT EDIT\n")
for n in names:
  agg.add("import commands/" & n & "/main as " & n.toLowerAscii() & "_cmd\n")
agg.add("\nimport kairosbot/plugin\n")
agg.add("\nproc registerAllPlugins*(platform: PluginPlatform) =\n")
for n in names:
  agg.add("  " & n.toLowerAscii() & "_cmd.register(newPluginContext(platform, \"" &
          n & "\", dir = \"commands/" & n & "\"))\n")

writeFile(outFile, agg)
echo "Generated ", outFile, " with ", $names.len, " plugin(s): ",
     names.join(", ")
